# Generated by Django 6.0.4 on 2026-04-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('content', models.TextField(verbose_name='问题内容')),
                ('answer', models.TextField(verbose_name='回答内容')),
                ('category', models.CharField(choices=[('LIFE', '生活'), ('TEACHING', '教学'), ('REGISTRATION', '报到')], max_length=20, verbose_name='分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '常见问题',
                'verbose_name_plural': '常见问题管理',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('major', models.CharField(max_length=100, verbose_name='录取专业')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('status', models.CharField(choices=[('UNREGISTERED', '未报到'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成')], default='UNREGISTERED', max_length=20, verbose_name='报到状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新生',
                'verbose_name_plural': '新生管理',
            },
        ),
        migrations.CreateModel(
            name='RegistrationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('PENDING', '未完成'), ('COMPLETED', '已完成')], default='PENDING', max_length=20, verbose_name='状态')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='myapp.student', verbose_name='关联新生')),
            ],
            options={
                'verbose_name': '报到任务',
                'verbose_name_plural': '报到任务管理',
            },
        ),
    ]
