# Generated by Django 6.0.4 on 2026-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='未分配', max_length=100, verbose_name='学院归属'),
        ),
    ]
