# Generated by Django 6.0.4 on 2026-04-23 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50, verbose_name='宿舍楼')),
                ('room', models.CharField(max_length=10, verbose_name='房间号')),
                ('total_beds', models.IntegerField(default=4, verbose_name='总床位')),
                ('available_beds', models.IntegerField(default=4, verbose_name='剩余床位')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='是否已满')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '宿舍',
                'verbose_name_plural': '宿舍管理',
            },
        ),
        migrations.CreateModel(
            name='StudentDormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('dormitory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='myapp.dormitory', verbose_name='宿舍')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory', to='myapp.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生宿舍分配',
                'verbose_name_plural': '学生宿舍分配管理',
            },
        ),
    ]
